//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvertisementList.EditAdvertisementWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class EditAdvertisementWebPart {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "14.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(EditAdvertisementWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControlTree(global::AdvertisementList.EditAdvertisementWebPart.EditAdvertisementWebPart @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("p\r\n"));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n<!--[if lt IE 7 ]><html class=\"ie ie6\" lang=\"en\"> <![endif]-" +
                        "->\r\n<!--[if IE 7 ]><html class=\"ie ie7\" lang=\"en\"> <![endif]-->\r\n<!--[if IE 8 ]>" +
                        "<html class=\"ie ie8\" lang=\"en\"> <![endif]-->\r\n<!--[if (gte IE 9)|!(IE)]><!--><ht" +
                        "ml lang=\"ru\"> <!--<![endif]-->\r\n\r\n<head>\r\n\t<meta charset=\"utf-8\">\r\n\t<title>Загол" +
                        "овок</title>\r\n\t<meta name=\"description\" content=\"\">\r\n\r\n\t<meta http-equiv=\"X-UA-C" +
                        "ompatible\" content=\"IE=edge\">\r\n\t<meta name=\"viewport\" content=\"width=device-widt" +
                        "h, initial-scale=1, maximum-scale=1\">\r\n\t\r\n\t<link rel=\"stylesheet\" href=\"../_layo" +
                        "uts/15/AdvertisementList/css/owl.carousel.min.css\">\r\n\t<link rel=\"stylesheet\" hre" +
                        "f=\"../_layouts/15/AdvertisementList/css/owl.theme.default.min.css\">\r\n\r\n\t<link re" +
                        "l=\"stylesheet\" href=\"../_layouts/15/AdvertisementList/libs/bootstrap/css/bootstr" +
                        "ap-grid.min.css\">\r\n\t<link href=\"https://fonts.googleapis.com/css?family=Roboto:3" +
                        "00,400,500,700,900&amp;subset=cyrillic,cyrillic-ext\" rel=\"stylesheet\">\r\n\t<link r" +
                        "el=\"stylesheet\" href=\"../_layouts/15/AdvertisementList/css/main.css\">\r\n\t<link re" +
                        "l=\"stylesheet\" href=\"../_layouts/15/AdvertisementList/css/media.css\">\r\n\r\n</head>" +
                        "\r\n\r\n<body>\r\n<div id=\"wrapper\">\r\n\t<div class=\"main bg-white\">\r\n\t\t<div class=\"topi" +
                        "ng-box\">\r\n\t\t\t<div class=\"container\">\r\n\t\t\t\t<ul class=\"pagin\">\r\n\t\t\t\t\t<li><a href=\"" +
                        "\">Главная</a></li>\r\n\t\t\t\t</ul>\r\n\t\t\t\t<div class=\"title\">Pending</div>\r\n\t\t\t</div>\r\n" +
                        "\t\t</div>\r\n\t\t<div class=\"container inactive\" id=\"main\">\r\n\t\t\t<div class=\"two-colum" +
                        "ns\">\r\n\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t<div class=\"col-md-9 col-sm-12\">\r\n\t\t\t\t\t\t<div c" +
                        "lass=\"content-box\">\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"section-padding\">\r\n\t\t\t\t\t\t\t\t<for" +
                        "m action=\"\" class=\"default-form edit-form\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t" +
                        "\t\t\t\t\t\t\t<p class=\"label\">Заголовок</p>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"edit-" +
                        "title\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<p class=\"la" +
                        "bel\">Категории</p>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" id=\"Categories\">\r\n\t\t\t" +
                        "\t\t\t\t\t\t\t\t<option value=\"\" disabled>Pending</option>\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t" +
                        "\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<p class=\"label\">Описание</p" +
                        ">\r\n\t\t\t\t\t\t\t\t\t\t<textarea class=\"edit-description\"></textarea>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t" +
                        "\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"file-upload\" class=\"custom-f" +
                        "ile-upload\">Select images (3 or less)</label>\r\n                                 " +
                        "       <input id=\"file-upload\" type=\"file\" multiple onchange=\"selectFiles()\"/>\r\n" +
                        "\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<ul class=\"download-i" +
                        "mages\">\r\n\t\t\t\t\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t" +
                        "\t\t\t\t\t<p class=\"label\">Объявление будет отправлено на модерацию</p>\r\n\t\t\t\t\t\t\t\t\t\t<i" +
                        "nput type=\"submit\" class=\"btn\" value=\"Сохранить\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t</fo" +
                        "rm>\r\n\t\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div class=\"col-md-3 col-s" +
                        "m-12\">\r\n\t\t\t\t\t\t<div class=\"aside aside-moved-top\">\r\n\t\t\t\t\t\t\t<div class=\"aside-box " +
                        "news-archive\">\r\n\t\t\t\t\t\t\t\t<div class=\"aside-title title\" id=\"status\">Pending</div>" +
                        "\r\n\t\t\t\t\t\t\t\t<a href=\"#change\" class=\"btn publish\" id=\"changeStatus\" onclick=\"publi" +
                        "shAdvertisement()\">Опубликовать</a>\r\n\t\t\t\t\t\t\t\t<ul class=\"month-list\">\r\n\t\t\t\t\t\t\t\t\t<" +
                        "li><a href=\"\">В архив</a></li>\r\n\t\t\t\t\t\t\t\t\t<li><a href=\"#delete\" onclick=\"deleteAd" +
                        "vertisement()\">Удалить</a></li  \r\n\t\t\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t" +
                        "\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n\t<div class=\"footer footer-" +
                        "inner\">\r\n\t\t<div class=\"container\">\r\n\t\t\t<div class=\"row\">\r\n\t\t\t\t<div class=\"col-sm" +
                        "-12\">\r\n\t\t\t\t\t<div class=\"wrap\">\r\n\t\t\t\t\t\t<div class=\"copy\">© 2018 РН Банк. Корпорат" +
                        "ивный портал сотрудников банка.</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</d" +
                        "iv>\r\n\t</div>\r\n</div>\r\n\r\n\r\n\t<!--[if lt IE 9]>\r\n\t<script src=\"libs/html5shiv/es5-s" +
                        "him.min.js\"></script>\r\n\t<script src=\"libs/html5shiv/html5shiv.min.js\"></script>\r" +
                        "\n\t<script src=\"libs/html5shiv/html5shiv-printshiv.min.js\"></script>\r\n\t<script sr" +
                        "c=\"libs/respond/respond.min.js\"></script>\r\n\t<![endif]-->\r\n\r\n\t<script src=\"../_la" +
                        "youts/15/AdvertisementList/libs/jquery/jquery-1.11.2.min.js\"></script>\r\n    <scr" +
                        "ipt src=\"../_layouts/15/AdvertisementList/utils/helper.js\"></script>\r\n    <scrip" +
                        "t src=\"../_layouts/15/AdvertisementList/js/editAdvertisement.js\"></script>\r\n\t<sc" +
                        "ript src=\"../_layouts/15/AdvertisementList/libs/plugins-scroll/plugins-scroll.js" +
                        "\"></script>\r\n\t<script src=\"../_layouts/15/AdvertisementList/js/owl.carousel.js\">" +
                        "</script>\r\n\t<script src=\"../_layouts/15/AdvertisementList/js/common.js\"></script" +
                        ">\r\n\t\r\n</body>\r\n</html>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
