//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvertisementList.EditAdvertisementWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class EditAdvertisementWebPart {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "14.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(EditAdvertisementWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControlTree(global::AdvertisementList.EditAdvertisementWebPart.EditAdvertisementWebPart @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n<!--[if lt IE 7 ]><html class=\"ie ie6\" lang=\"en\"> <![endif]-" +
                        "->\r\n<!--[if IE 7 ]><html class=\"ie ie7\" lang=\"en\"> <![endif]-->\r\n<!--[if IE 8 ]>" +
                        "<html class=\"ie ie8\" lang=\"en\"> <![endif]-->\r\n<!--[if (gte IE 9)|!(IE)]><!--><ht" +
                        "ml lang=\"ru\"> <!--<![endif]-->\r\n\r\n<head>\r\n\t<meta charset=\"utf-8\">\r\n\t<title>Загол" +
                        "овок</title>\r\n\t<meta name=\"description\" content=\"\">\r\n\r\n\t<meta http-equiv=\"X-UA-C" +
                        "ompatible\" content=\"IE=edge\">\r\n\t<meta name=\"viewport\" content=\"width=device-widt" +
                        "h, initial-scale=1, maximum-scale=1\">\r\n\t\r\n\t<link rel=\"stylesheet\" href=\"../_layo" +
                        "uts/15/AdvertisementList/css/owl.carousel.min.css\">\r\n\t<link rel=\"stylesheet\" hre" +
                        "f=\"../_layouts/15/AdvertisementList/css/owl.theme.default.min.css\">\r\n\r\n\t<link re" +
                        "l=\"stylesheet\" href=\"../_layouts/15/AdvertisementList/libs/bootstrap/css/bootstr" +
                        "ap-grid.min.css\">\r\n\t<link href=\"https://fonts.googleapis.com/css?family=Roboto:3" +
                        "00,400,500,700,900&amp;subset=cyrillic,cyrillic-ext\" rel=\"stylesheet\">\r\n\t<link r" +
                        "el=\"stylesheet\" href=\"../_layouts/15/AdvertisementList/css/main.css\">\r\n\t<link re" +
                        "l=\"stylesheet\" href=\"../_layouts/15/AdvertisementList/css/media.css\">\r\n\r\n</head>" +
                        "\r\n\r\n<body>\r\n<div id=\"wrapper\">\r\n\t<div class=\"main bg-white\">\r\n\t\t<div class=\"topi" +
                        "ng-box\">\r\n\t\t\t<div class=\"container\">\r\n\t\t\t\t<ul class=\"pagin\">\r\n\t\t\t\t\t<li><a href=\"" +
                        "\">Главная</a></li>\r\n\t\t\t\t</ul>\r\n\t\t\t\t<div class=\"title\">Редактирование объявления<" +
                        "/div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t\t<div class=\"container\">\r\n\t\t\t<div class=\"two-column" +
                        "s\">\r\n\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t<div class=\"col-md-9 col-sm-12\">\r\n\t\t\t\t\t\t<div cl" +
                        "ass=\"content-box\">\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"section-padding\">\r\n\t\t\t\t\t\t\t\t<form" +
                        " action=\"\" class=\"default-form edit-form\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t" +
                        "\t\t\t\t\t\t<p class=\"label\">Заголовок</p>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\">\r\n\t\t\t\t\t\t\t\t\t</" +
                        "div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<p class=\"label\">Категории</p>\r\n" +
                        "\t\t\t\t\t\t\t\t\t\t<select class=\"cat-select\">\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"\"></option>\r\n\t\t" +
                        "\t\t\t\t\t\t\t\t\t<option value=\"\">Категории</option>\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</di" +
                        "v>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<p class=\"label\">Описание</p>\r\n\t\t\t" +
                        "\t\t\t\t\t\t\t<textarea></textarea>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t" +
                        "\t\t\t\t\t\t\t\t\t<p class=\"label\">Фотографии, не более 3</p>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"file" +
                        "\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input id=\"file4\" type=\"file\" title=\"Загрузите фото\" />\r\n\t\t\t\t\t\t\t\t" +
                        "\t\t\t<span class=\"file-input-text\">name.png</span>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</d" +
                        "iv>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<ul class=\"download-images\">\r\n\t\t\t" +
                        "\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"../_layouts/15/AdvertisementList/img/2.png\" " +
                        "alt=\"\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"delete\"></span>\r\n\t\t\t\t\t\t\t\t\t\t\t</li>\r\n\t\t\t\t\t\t\t\t\t\t\t" +
                        "<li>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"../_layouts/15/AdvertisementList/img/2.png\" alt=\"\">\r" +
                        "\n\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"delete\"></span>\r\n\t\t\t\t\t\t\t\t\t\t\t</li>\r\n\t\t\t\t\t\t\t\t\t\t</ul>\r\n\t\t" +
                        "\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<p class=\"label\">Объявл" +
                        "ение будет отправлено на модерацию</p>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"bt" +
                        "n\" value=\"Сохранить\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t</form>\r\n\t\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t" +
                        "</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div class=\"col-md-3 col-sm-12\">\r\n\t\t\t\t\t\t<div class=\"as" +
                        "ide aside-moved-top\">\r\n\t\t\t\t\t\t\t<div class=\"aside-box news-archive\">\r\n\t\t\t\t\t\t\t\t<div" +
                        " class=\"aside-title title\">Объявление на модерации</div>\r\n\t\t\t\t\t\t\t\t<a href=\"\" cla" +
                        "ss=\"btn\">Опубликовать</a>\r\n\t\t\t\t\t\t\t\t<ul class=\"month-list\">\r\n\t\t\t\t\t\t\t\t\t<li><a href" +
                        "=\"\">Редактировать</a></li>\r\n\t\t\t\t\t\t\t\t\t<li><a href=\"\">В архив</a></li>\r\n\t\t\t\t\t\t\t\t\t<" +
                        "li><a href=\"\">Удалить</a></li>\r\n\t\t\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t" +
                        "\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n\t<div class=\"footer footer-in" +
                        "ner\">\r\n\t\t<div class=\"container\">\r\n\t\t\t<div class=\"row\">\r\n\t\t\t\t<div class=\"col-sm-1" +
                        "2\">\r\n\t\t\t\t\t<div class=\"wrap\">\r\n\t\t\t\t\t\t<div class=\"copy\">© 2018 РН Банк. Корпоратив" +
                        "ный портал сотрудников банка.</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div" +
                        ">\r\n\t</div>\r\n</div>\r\n\r\n\r\n\t<!--[if lt IE 9]>\r\n\t<script src=\"libs/html5shiv/es5-shi" +
                        "m.min.js\"></script>\r\n\t<script src=\"libs/html5shiv/html5shiv.min.js\"></script>\r\n\t" +
                        "<script src=\"libs/html5shiv/html5shiv-printshiv.min.js\"></script>\r\n\t<script src=" +
                        "\"libs/respond/respond.min.js\"></script>\r\n\t<![endif]-->\r\n\r\n\t<script src=\"../_layo" +
                        "uts/15/AdvertisementList/libs/jquery/jquery-1.11.2.min.js\"></script>\r\n\t<script s" +
                        "rc=\"../_layouts/15/AdvertisementList/libs/plugins-scroll/plugins-scroll.js\"></sc" +
                        "ript>\r\n\t<script src=\"../_layouts/15/AdvertisementList/js/owl.carousel.js\"></scri" +
                        "pt>\r\n\t<script src=\"../_layouts/15/AdvertisementList/js/common.js\"></script>\r\n\t\r\n" +
                        "</body>\r\n</html>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
