//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvertisementList.FullAdvertisementWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class FullAdvertisementWebPart {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "14.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(FullAdvertisementWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControlTree(global::AdvertisementList.FullAdvertisementWebPart.FullAdvertisementWebPart @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n<!--[if lt IE 7 ]><html class=\"ie ie6\" lang=\"en\"> <![endif]-" +
                        "->\r\n<!--[if IE 7 ]><html class=\"ie ie7\" lang=\"en\"> <![endif]-->\r\n<!--[if IE 8 ]>" +
                        "<html class=\"ie ie8\" lang=\"en\"> <![endif]-->\r\n<!--[if (gte IE 9)|!(IE)]><!--><ht" +
                        "ml lang=\"ru\"> <!--<![endif]-->\r\n\r\n<head>\r\n\t<meta charset=\"utf-8\">\r\n\t<title>Загол" +
                        "овок</title>\r\n\t<meta name=\"description\" content=\"\">\r\n\r\n\t<meta http-equiv=\"X-UA-C" +
                        "ompatible\" content=\"IE=edge\">\r\n\t<meta name=\"viewport\" content=\"width=device-widt" +
                        "h, initial-scale=1, maximum-scale=1\">\r\n\t\r\n\t<link rel=\"stylesheet\" href=\"../_layo" +
                        "uts/15/AdvertisementList/css/owl.carousel.min.css\">\r\n\t<link rel=\"stylesheet\" hre" +
                        "f=\"../_layouts/15/AdvertisementList/css/owl.theme.default.min.css\">\r\n\r\n\t<link re" +
                        "l=\"stylesheet\" href=\"../_layouts/15/AdvertisementList/libs/bootstrap/css/bootstr" +
                        "ap-grid.min.css\">\r\n\t<link href=\"https://fonts.googleapis.com/css?family=Roboto:3" +
                        "00,400,500,700,900&amp;subset=cyrillic,cyrillic-ext\" rel=\"stylesheet\">\r\n\t<link r" +
                        "el=\"stylesheet\" href=\"../_layouts/15/AdvertisementList/css/main.css\">\r\n\t<link re" +
                        "l=\"stylesheet\" href=\"../_layouts/15/AdvertisementList/css/media.css\">\r\n</head>\r\n" +
                        "\r\n<body>\r\n<div id=\"wrapper\">\r\n\t<div class=\"main bg-white\">\r\n\t\t<div class=\"toping" +
                        "-box\">\r\n\t\t\t<div class=\"container\">\r\n\t\t\t\t<ul class=\"pagin\">\r\n\t\t\t\t\t<li><a href=\"\">" +
                        "Главная</a></li>\r\n\t\t\t\t\t<li><a href=\"\">Кредитный департамент</a></li>\r\n\t\t\t\t\t<li><" +
                        "a href=\"\">Кредитный департамент</a></li>\r\n\t\t\t\t</ul>\r\n\t\t\t\t<div class=\"title\">Pend" +
                        "ing</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t\t<div class=\"container\">\r\n\t\t\t<div class=\"two-co" +
                        "lumns\">\r\n\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t<div class=\"col-md-9 col-sm-12\">\r\n\t\t\t\t\t\t<di" +
                        "v class=\"content-box\">\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"desk-item-box section-paddin" +
                        "g\">\r\n\t\t\t\t\t\t\t\t<div class=\"hh\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"date\">Pending</div>\r\n\t\t\t\t\t\t\t" +
                        "\t\t<div class=\"who\">\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"img\"><img src=" +
                        "\"../_layouts/15/AdvertisementList/img/new1.png\" alt=\"\"></div>\r\n\t\t\t\t\t\t\t\t\t\t<div cl" +
                        "ass=\"name\">Pending</div>\r\n\t\t\t\t\t\t\t\t\t\t</a>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t" +
                        "\t\t\t<div class=\"row desk-photos\">\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t<div class=" +
                        "\"text\">\r\n\t\t\t\t\t\t\t\t\t<p>Pending</p>\r\n\t\t\t\t\t\t\t\t\t<a href=\"\" class=\"link\">Contact</a>\r\n" +
                        "\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div class=\"col" +
                        "-md-3 col-sm-12\">\r\n\t\t\t\t\t\t<div class=\"aside aside-moved-top\">\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<d" +
                        "iv class=\"aside-box fast-links\">\r\n\t\t\t\t\t\t\t\t<div class=\"aside-title title\">Быстрые" +
                        " ссылки</div>\r\n\t\t\t\t\t\t\t\t<ul class=\"list\">\r\n\t\t\t\t\t\t\t\t\t<li><a href=\"\">Анонсы</a></li" +
                        ">\r\n\t\t\t\t\t\t\t\t\t<li><a href=\"\">Оргструктура</a></li>\r\n\t\t\t\t\t\t\t\t\t<li><a href=\"\">Онлайн" +
                        " библиотека</a></li>\r\n\t\t\t\t\t\t\t\t\t<li><a href=\"\">Объявления</a></li>\r\n\t\t\t\t\t\t\t\t</ul>" +
                        "\r\n\t\t\t\t\t\t\t\t<a href=\"\" class=\"like\">Скажи спасибо</a>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div " +
                        "class=\"aside-box birthday-box\">\r\n\t\t\t\t\t\t\t\t<div class=\"aside-title title\">Ближайши" +
                        "е дни рождения</div>\r\n\t\t\t\t\t\t\t\t<ul class=\"list\">\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<div c" +
                        "lass=\"img\"><a href=\"\"><img src=\"../_layouts/15/AdvertisementList/img/face.png\" a" +
                        "lt=\"\"></a></div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"tt\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"date\">26 ма" +
                        "рта</div>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"name\"><a href=\"\">Анна Ефремова</a></div>\r\n\t\t\t\t" +
                        "\t\t\t\t\t\t\t<div class=\"fah\">Дизайнер</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</li>\r\n\t\t\t\t\t\t" +
                        "\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"img\"><a href=\"\"><img src=\"../_layouts/15/Advertis" +
                        "ementList/img/face.png\" alt=\"\"></a></div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"tt\">\r\n\t\t\t\t\t\t\t\t\t" +
                        "\t\t<div class=\"date\">26 марта</div>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"name\"><a href=\"\">Анна" +
                        " Ефремова</a></div>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"fah\">Дизайнер</div>\r\n\t\t\t\t\t\t\t\t\t\t</div" +
                        ">\r\n\t\t\t\t\t\t\t\t\t</li>\r\n\t\t\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t\t\t\t<a href=\"\" class=\"more-link\">Показать " +
                        "больше</a>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t<" +
                        "/div>\r\n\t</div>\r\n\t<div class=\"footer footer-inner\">\r\n\t\t<div class=\"container\">\r\n\t" +
                        "\t\t<div class=\"row\">\r\n\t\t\t\t<div class=\"col-sm-12\">\r\n\t\t\t\t\t<div class=\"wrap\">\r\n\t\t\t\t\t" +
                        "\t<div class=\"copy\">© 2018 РН Банк. Корпоративный портал сотрудников банка.</div>" +
                        "\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n\r\n\r\n\t<!--[if lt" +
                        " IE 9]>\r\n\t<script src=\"libs/html5shiv/es5-shim.min.js\"></script>\r\n\t<script src=\"" +
                        "libs/html5shiv/html5shiv.min.js\"></script>\r\n\t<script src=\"libs/html5shiv/html5sh" +
                        "iv-printshiv.min.js\"></script>\r\n\t<script src=\"libs/respond/respond.min.js\"></scr" +
                        "ipt>\r\n\t<![endif]-->\r\n\r\n\t<script src=\"../_layouts/15/AdvertisementList/libs/jquer" +
                        "y/jquery-1.11.2.min.js\"></script>\r\n    <script src=\"../_layouts/15/Advertisement" +
                        "List/utils/helper.js\"></script>\r\n    <script src=\"../_layouts/15/AdvertisementLi" +
                        "st/js/fullAdvertisement.js\"></script>\r\n\t<script src=\"../_layouts/15/Advertisemen" +
                        "tList/libs/plugins-scroll/plugins-scroll.js\"></script>\r\n\t<script src=\"../_layout" +
                        "s/15/AdvertisementList/js/owl.carousel.js\"></script>\r\n\t<script src=\"../_layouts/" +
                        "15/AdvertisementList/js/common.js\"></script>\r\n\t\r\n</body>\r\n</html>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
